FROM docker.arvancloud.ir/python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y ncat \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY entrypoint-api.sh /usr/src/app/entrypoint-api.sh
RUN chmod +x /usr/src/app/entrypoint-api.sh

ENTRYPOINT ["/usr/src/app/entrypoint-api.sh"]
